language: node_js

jobs:
  include:
    - stage: test
      name: Build
      script: yarn run build-dev
    - # Still on test stage
      name: Bundle size
      script: yarn run bundlesize
    - # Still on test stage
      name: Lint
      script: yarn run lint
    # Define the release stage that runs semantic-release
    - stage: deploy
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
