name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - eslint
          - prettier

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: yarn
      - run: |
          yarn lint:${{ matrix.linter }}

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version:
          - 10
          - 12

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - run: yarn
      - run: yarn test

  publish:
    runs-on: ubuntu-latest
    needs:
    - lint
    - test

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn
    - name: Run Sematic release
      working-directory: ./gatsby-image-gallery
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
