name: Hacktoberfest

on:
  schedule:
    - cron: "0 0 * 10 *"
  workflow_dispatch:
    inputs:
      revert:
        description: 'If label should be set or unset'
        required: true
        default: '1'

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - uses: browniebroke/hacktoberfest-labeler-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          revert: ${{ github.event.inputs.revert }}"
