name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build main lib
      run: |
        yarn
        yarn link
      env:
        CI: true
    - name: Build example
      run: |
        cd example
        yarn link @browniebroke/gatsby-image-gallery
        yarn
        yarn build
      env:
        CI: true
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@master
      with:
        build_dir: example/public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
